#!/usr/bin/env python3
import argparse
import os
import sys
import fitanimate as fa
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def main():            
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'infile', metavar='FITFILE', type=argparse.FileType(mode='rb'),
        help='Input .FIT file (Use - for stdin)',
    )
    parser.add_argument(
        '--offset', type=float, default=9.0, help='Time offset (hours)'
    )
    parser.add_argument(
        '--show',    '-s', action='store_true', default=False, help='Show animation'
    )
    parser.add_argument(
        '--num',    '-n', type=int, default=0, help='Only animate th first N frames'
    )
    parser.add_argument(
        '--outfile', '-o', type=str, default=None, help='Output filename'
    )
    parser.add_argument(
        '--format', '-f', type=str, default='4k', help='Output file format. Valid values are 4k or 1080p'
    )
    parser.add_argument(
        '--vertical', '-v', action='store_true', default=False, help='Plot bars Verticaly'
    )
    args = parser.parse_args()

    if args.format == '480p':
        x = 7.20
        y = 4.80
        fontSize=12
    elif args.format == '720p':
        x=12.80
        y=7.20
        fontSize=20
    elif args.format == '1080p':
        x=19.20
        y=10.80
        fontSize=32
    elif args.format == '4k':
        x=38.40
        y=21.60
        fontSize=64
    else:
        print( 'Unkown output format {}'.format(args.format) )
        sys.exit(1)

    plt.rcParams.update({'font.size': fontSize})


    fig = plt.figure(figsize=(x,y))
    gs = fig.add_gridspec( nrows=5, ncols=1)
    a_t   = fig.add_subplot( gs[0:4,0] )
    a_bar = fig.add_subplot( gs[4,0] )

    fig.patch.set_alpha(0.) # Transparant background

    # See https://adrian.pw/blog/matplotlib-transparent-animation/
    plotVars = []
    plotVars.append( fa.PlotVar('cadence', 'Cadence', 'RPM', 120.0 ) )
    plotVars.append( fa.PlotVar('speed', 'Speed', 'km/h', 80.0, scaleFactor=3.6 ) )
    plotVars.append( fa.PlotVar('power', 'Power',' W', 1000.0))

    if args.vertical:
        plt.subplots_adjust(bottom=0.06, left=0.0, right=1.0, top=1.0)
        plotBar = fa.BarPlot( plotVars, a_bar )
        plotText = fa.TextPlot( a_t, x=0.02 )
    else:
        plt.subplots_adjust(bottom=0.0, left=0.11, right=1.0, top=1.0)
        plotBar = fa.HBarPlot( plotVars, a_bar )
        plotText = fa.TextPlot( a_t )

    plots = (plotBar, plotText)

    record_names = []
    for plot in plots:
        record_names += plot.ffNames()

    dataGen = fa.DataGen( fa.prePocessData(args.infile, int(args.offset*3600.0), record_names ) )

    nData = dataGen.dataSet.nFrames()
    if args.num:
        nData = args.num

    # Time interval between frames in msec.
    inter = 1000.0/float(dataGen.dataSet.fps)
    anim=animation.FuncAnimation(fig, fa.run, dataGen, fargs=(fig,plots,), repeat=False,blit=False,interval=inter,save_count=nData)

    outf = os.path.splitext(os.path.basename(args.infile.name))[0] + '_overlay.mp4'
    if args.outfile:
        outf = args.outfile

    if not args.show:    
        anim.save(outf, codec="png", fps=dataGen.dataSet.fps,
                  savefig_kwargs={'transparent': True, 'facecolor': 'none'})

    if args.show:
        plt.show()

if __name__ == '__main__':
    main()
